---
name: Ansible and YAML Lint

on:
  push:

jobs:
  check-syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Ansible list
        uses: ansible/ansible-lint-action@master
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v2
