---
name: Ansible and YAML Lint

on: [push, pull_request]    # yamllint disable-line rule:truthy

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Ansible list
        uses: ansible/ansible-lint-action@v4.1.0
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v2
